name: Deploy

on:
  push:
    branches:
      - master

jobs:
  setup:
    runs-on: [self-hosted]

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v2

      - name: setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Setup project
        run: |
          docker-compose stop
          docker-compose -f docker-compose.override.yml build
          docker-compose -f docker-compose.override.yml up -d
